//
// Generated by JTB 1.3.2
//

package minijava_syntaxtree;

import minijava_syntaxtree.Node;

/**
 * The interface which NodeList, NodeListOptional, and NodeSequence
 * implement.
 */
public interface NodeListInterface extends Node {
   public void addNode(Node n);
   public Node elementAt(int i);
   public java.util.Enumeration<Node> elements();
   public int size();

   public void accept(minijava_visitor.Visitor v);
   public <R,A> R accept(minijava_visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(minijava_visitor.GJNoArguVisitor<R> v);
   public <A> void accept(minijava_visitor.GJVoidVisitor<A> v, A argu);
}

