//
// Generated by JTB 1.3.2
//

package spiglet_syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(spiglet_visitor.Visitor v);
   public <R,A> R accept(spiglet_visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(spiglet_visitor.GJNoArguVisitor<R> v);
   public <A> void accept(spiglet_visitor.GJVoidVisitor<A> v, A argu);
}

